config/routes.rb
Rails.application.routes.draw do
  
  # Pages
  root 'pages#home'
  get '/about', to: 'pages#about' 

  # Contact
  resources :contacts, only: [:new, :create]
  
  # User Auth
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'

  # Projects
  get '/projects', to: 'projects#index'
  get '/javascript-projects', to: 'projects#javascript'
  get '/ruby-on-rails-projects', to: 'projects#rails'
  get '/ios-projects', to: 'projects#ios'
  
  # Blogs
  resources :blogs
  resource :pages do
    collection do
      post :search, to: 'pages#search'
    end
  end
  
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  
  belongs_to :user
  
  validates :title, presence: true, uniqueness: true, length: { minimum: 2}
  validates :body, presence: true, uniqueness: true, length: { minimum: 2 }
  validates :topic, presence: true
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  
  validates :name, presence: true, length: {maximum: 150}
  validates :comments, presence: true, length: {maximum: 1000}
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 150 },
                      uniqueness: { case_sensitive: false },
                      format: { with: VALID_EMAIL_REGEX }

end

app/models/project.rb
class Project < ActiveRecord::Base
  
  belongs_to :user
  
  validates :title, presence: true, uniqueness: true, length: { minimum: 2, maximum: 30 }
  validates :description, presence: true, uniqueness: true, length: {minimum: 5, maximum: 500 }
  validates :points, presence: true, uniqueness: true, length: {minimum: 5, maximum: 5000 }
  validates :github, presence: true, uniqueness: true, length: { minimum: 10, maximum: 200 }
  validates :live_link, length: { maximum: 200 }
  validates :image, length: { maximum: 100 }
  validates :project_type, presence: true, length: {maximum: 20}
 
  
end

app/models/rails_project.rb
class Project < ActiveRecord::Base
  
  belongs_to :user
  
  validates :title, presence: true, uniqueness: true, length: { minimum: 2, maximum: 30 }
  validates :description, presence: true, uniqueness: true, length: {minimum: 5, maximum: 500 }
  validates :points, presence: true, uniqueness: true, length: {minimum: 5, maximum: 5000 }
  validates :github, presence: true, uniqueness: true, length: { minimum: 10, maximum: 100 }
  validates :live_link, presence: true, uniqueness: true, length: { minimum: 10, maximum: 100 }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :blogs
  has_many :projects
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
                      uniqueness: { case_sensitive: false },
                      format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    return if logged_in?
    flash[:danger] = 'You must be logged in to perform that action.'
    redirect_to blogs_path
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  include BlogsHelper

  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]

  # GET /blogs
  def index
    @blogs = Blog.paginate(page: params[:page], per_page: 7)
  end

  # GET /blogs/1
  def show
    @blogs = Blog.all
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        create_blog_file(@blog)
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def blog_params
    params.require(:blog).permit(:title, :body, :image, :topic)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)
    
    if @contact.save
      name = params[:contact][:name]
      email = params[:contact][:email]
      comments = params[:contact][:comments]
      
      ContactMailer.contact_email(name, email, comments).deliver

      redirect_to new_contact_path, notice: "Your message was sent successfully! 
      I'll get back to you as soon as possible."
    else
      redirect_to new_contact_path, notice: "Oops, an error occured. Are you sure you 
      did not leave a field blank?"
    end
    
  end
  
  private
    def contact_params
      # "white listing" these parameters
      params.require(:contact).permit(:name, :email, :comments)
    end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      
      session[:user_id] = user.id
      flash[:success] = "Welcome #{user.email}! You are now logged in."
      redirect_to blogs_path
      
    else
      flash.now[:danger] = "Your email address or password does not match."
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You are now logged out."
    redirect_to root_path
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
  def about
  end
  
  def search
    @blogs = Blog.search(params[:search_blogs]).order("created_at DESC")
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  include ProjectsHelper

  def index
    if params[:project_type]
      filter_projects(project_params)
    else
      @projects = Project.where.not("project_type LIKE ?", "%iOS%").reverse
    end
  end

  private

    def project_params
      params.require(:project_type)
    end
  
end

app/helpers/blogs_helper.rb
module BlogsHelper

	def create_blog_file(blog)
		title = blog.title.downcase.gsub(/[ .]/, '_')

		blog_file = File.new("db/blog_posts/#{title}.rb", 'w+')

		blog_file.puts "Blog.create!(\n\ttitle: '#{blog.title}',\n\tbody: '#{blog.body}',\n\ttopic: '#{blog.topic}',\n\tcreated_at: '#{blog.created_at}'\n)"

		blog_file.close
	end

end

app/helpers/projects_helper.rb
module ProjectsHelper
	def filter_projects(project_type)
		if !params[:project_type]
      @projects = Project.all

    elsif params[:project_type] == 'JavaScript'
      @projects = Project.where("project_type LIKE ?", '%JavaScript%').reverse

    elsif params[:project_type] == 'Ruby on Rails'
      @projects = Project.where("project_type LIKE ?", '%Rails%').reverse

    elsif params[:project_type] == 'iOS'
      @projects = Project.where("project_type LIKE ?", '%iOS%').reverse

    else
      params[:project_type] = nil
      @projects = Project.all.reverse
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <div class="row">
    <div class="col s12 m6 offset-m3">
      <% if @blog.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>
    
          <ul>
          <% @blog.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="input-field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div>
      
      <div class="input-field">
        <%= f.label :topic %><br>
        <%= f.text_field :topic %>
      </div>
      
      <div class="input-field">
        <%= f.label :body %><br>
        <%= f.text_area :body, class: "materialize-textarea" %>
      </div>
      
      
      <div class="actions center">
        <%= f.submit class: "btn waves-effect waves-light" %>
      </div>
      
    </div>
  </div>
<% end %>

app/views/blogs/_lookup.html.erb
<%= form_tag(search_pages_path, role: "search") do %>
  <div class="form-group row no-padding text-center col-md-12">
    
    <div class="col-md-10">
      <%= text_field_tag :search_blogs, nil, placeholder: "Search blog posts", autofocus: true,
                                                        class: 'form-control search-box input-lg' %>
    </div>
    
    <div class="col-md-2 center">
      <%= submit_tag "Search Posts", class: 'btn btn-lg btn-success' %>
    </div>
    
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1 class="center">Editing Blog</h1>

<%= render 'form' %>

<p class="center"> 
  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</p>

app/views/blogs/index.html.erb
<h5 class="pink-text text-darken-2 center">
  <p id="notice"><%= notice %></p>
</h5>

<section class="blog-font">
  <h1 class="center">Blog </h1>
  <!--Intro Card-->
  <div class="row">
    <div class="col s12 m6 offset-m3">
      <div class="card pink lighten-3">
        <div class="card-content white-text center">
            <p>
            This blog serves as my personal notebook for topics I've come across during 
            my learning experience, as well as a reference for ongoing projects. I hope they can teach 
            you something as well. Feel free to reach out for suggestions, I'm still learning!</p>
          </div>
        </div>
        
        <!-- < render 'blogs/lookup' %> -->
          
        </div>
      </div>
    </div>
  </div>
  
  <div class="col s12 center pagination">
    <%= will_paginate @blogs %>
  </div>
  
  <!--Cards-->
  <% @blogs.sort_by{|item| item.created_at}.reverse.each do |blog| %>
    <div class="row">
      <div class="col s12 m6 offset-m3">
        <div class="card white-text center">
          <div class="card-content white-text center">
            <span class="blog-topic"><%= blog.topic %></span>
            </br>
            <span class="card-title">
              <!--Title-->
              <%= link_to blog.title, blog_path(blog) %>
            </span>
            <!--Date-->
            <p><%= link_to blog.created_at.strftime("%B %e, %Y"), blog_path(blog) %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  
  <div class="col s12 center pagination">
    <%= will_paginate @blogs %>
  </div>
  
</section>

app/views/blogs/new.html.erb
<h1 class="center">New Blog</h1>

<%= render 'form' %>

<p class="center"> 
  <%= link_to 'Back', blogs_path %>
</p>

app/views/blogs/show.html.erb
<div class="row">
  <div class="blog-post-bg z-depth-1 col s12 m8 offset-m2 l6 offset-l3">
    <h2 class="center"> 
      <span class="blog-title"><%= @blog.title %></span>
    </h2>
    <p class="center"><%= @blog.created_at.strftime("%B %d, %Y") %></p>
    <%= raw(@blog.body) %>
  </div>
</div>

<div class="row col s12 center">
  <%= link_to 'Back to Blog Posts', blogs_path, class: "btn waves-effect waves-light" %>
</div>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <div class="row">
    <div class="col s12 m6 offset-m3">
      <% if @contact.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this message from being sent:</h2>
    
          <ul>
          <% @contact.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="input-field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      
      <div class="input-field">
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </div>
      
      <div class="input-field">
        <%= f.label :comments %><br>
        <%= f.text_area :comments, class: "materialize-textarea" %>
      </div>
      
      <button class="waves-effect waves-light btn-large" type="submit" name="action">Send Message</button>
    </div>
  </div>
<% end %>

app/views/contacts/new.html.erb
<h5 class="pink-text text-darken-2 center">
  <p id="notice"><%= notice %></p>
</h5>
           
<div class="center">
  <h1>Leave a Message</h1>
  
  <p>Feel free to get in touch for feedback on my projects or for interesting opportunities!</p>

  <%= render 'form' %>

  <p><%= link_to 'Back', root_path %></p>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="footer-copyright center">
    <div class="container">
      Copyright © 2016 Sandra Hallie
      <div class="white-text text-lighten-4 right">
        <%= link_to 'https://linkedin.com/in/sanlouise' do %>
          <i class="fa fa-linkedin fa-2x"></i>
        <% end %>

       | 
        
        <%= link_to 'https://github.com/sanlouise' do %>
          <i class="fa fa-github fa-2x"></i>
        <% end %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_head.html.erb
<title>Sandra Hallie</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<!--Import Google Icon Font-->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<%= csrf_meta_tags %>
<!--Let browser know website is optimized for mobile-->
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

app/views/layouts/_nav.html.erb
<nav>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="fa fa-bars"></i></a>
    
    <nav>
      <div class="nav-wrapper pink darken-1">
        <a href="/" class="brand-logo center">Sandra Hallie</a>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to "Projects", projects_path %></li>
          <li><%= link_to "Blog", blogs_path %></li>
          <li><%= link_to "Contact", new_contact_path %></li>
          
          <% if current_user %>
            <ul class="right hide-on-med-and-down">
              <li>Admin</li>
            </ul>
          <% end %>
          
        </ul>
      </div>
    </nav>

    <ul class="side-nav" id="mobile-demo">
      <li><%= link_to "Projects", projects_path %></li>
      <li><%= link_to "Blog", blogs_path %></li>
      <li><%= link_to "Contact", new_contact_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= render 'layouts/head' %>
</head>
<body>
  <header>
    <%= render 'layouts/nav' %>
	</header>

	<main>
		<div id="content">
		  <%= yield %>	 
		</div>
	</main>

	<%= render 'layouts/footer' %>

	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	
</body>
</html>

app/views/logins/new.html.erb
<h2 class="center red-text">Login</h2>

<div class="row">
  <div class="col m4 offset-m4 center">  
    <%= form_tag '/login' do %>
      
      <div class="input-field">
        <%= label_tag :email %>
        <%= text_field_tag :email %>
      </div>
      
      <div class="input-field">
        <%= label_tag :password %>
        <%= password_field_tag :password %>
      </div>
      
      <%= submit_tag 'Login', class: 'btn waves-effect waves-light' %>
      
    <% end %>
  </div>
</div>

app/views/pages/about.html.erb
<section id="main-features" class="section main-feature-gray">
  <div class="container">

    <div class="row">   
      <div class="col-md-8 col-sm-8 wow fadeInLeft">
        <div class="feature-item">
          <h3 class="title-small center">
            About
          </h3>
          <p>
            I was born and raised in the Netherlands. I moved to Rome, Italy after High School to study International Affairs and Business Administration at at American University.
          </p>
          <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book
          </p>
        </div>
      </div>
      

    </div>

  </div>
</section>

app/views/pages/home.html.erb
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br><br>
      <h1 class="header center text-lighten-2 home">Sandra Hallie</h1>
      <div class="row center">
        <h4 class="header col s12 white-text">- Full Stack Web Developer -</h4>
      </div>
    </div>
  </div>
  <div class="parallax">
    <%= image_tag("pexels3.jpeg") %>
  </div>
  </div> 
</div>

<div class="container">
  <div class="section">
    <div class="row">
      <div class="col m8 offset-m2 s12 center">
        <h3 class="brown-text"> - About - </h3>

        <p>I am a Full Stack web developer, addicted to learning about new web technologies. I live and breathe code. 
        When I am not coding, I am either watching tutorial videos or listening to tech podcasts. </p> 
        <p>I was born and raised in the Netherlands and hold degrees in Business Administration and International 
        Affairs from an American university in Rome, Italy.
        </p> 
        <a href="/projects" class="btn-large waves-effect waves-light pink darken-1">Portfolio</a>
        </br>
      </div>
      
    </div>
  </div>
</div>


<div class="parallax-container valign-wrapper">
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <div class="row">
          <div class="col s12 center">
            <a href="/contacts/new" id="download-button" class="btn-large waves-effect waves-light pink darken-1">Get in Touch</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  
    <div class="parallax">
      <%= image_tag("pexels3.jpeg") %>
    </div>
    
</div>

app/views/pages/search.html.erb
<section class="blog-font">

  <h1 class="center">Blog</h1>
  <h4 class="center">Search Results</h4>

  <!--Intro Card-->
  <div class="row">
    <div class="col s12 m6 offset-m3">
        
      <%= render 'blogs/lookup' %>
        
    </div>
  </div>
  
  <% if @blogs.any? %>
    <!--Cards-->
    <% @blogs.sort_by{|item| item.created_at}.reverse.each do |blog| %>

      <div class="row">
        <div class="col s12 m6 offset-m3">
          <div class="card white-text center">

            <!--Image-->
            <div class="card-image waves-effect waves-block waves-light">
              <%= link_to image_tag(blog.image), blog_path(blog) if blog.image %>
            </div>

            <div class="card-content white-text center">

              <!-- Topic -->
              <span class="blog-topic"><%= blog.topic %></span>

              </br>
              
              <!--Title-->
              <span class="card-title"><%= link_to blog.title, blog_path(blog) %></span>

              <!--Date-->
              <p><%= link_to blog.created_at.strftime("%B %e, %Y"), blog_path(blog) %></p>

            </div>

          </div>
        </div>
      </div>

    <% end %>

  <% else %>

    <div class="row">
      <div class="col s12 m6 offset-m3 center">
        <h5> Oops, no posts match your search criteria.</h5>
      </div>
    </div>

  <% end %>
  
  <div class="row">
    <div class="col-md-2 center">
      <%= link_to "Back To All Posts", blogs_path, class: "waves-effect waves-light btn" %>
    </div>
  </div>

</section>

app/views/projects/_projects.html.erb
<!--Iterate through Projects-->
<% projects.each do |project| %>
  <hr/>
  <div class="row">
    <div class="col s12">
      <div class="col s12 l7">
        <!--Project Title-->
        <h3 class="center"><%= project.title %></h3>
        <!--Project Description-->
        <p><%= project.description %></p>
        <!--Project Points-->
        <ul class="portfolio">
          <%= project.points.html_safe %>
        </ul>
        <!--GitHub link-->
        <p>
          <i class="fa fa-github"></i> <%= link_to "GitHub Repository", project.github %>
        </p>
      </div>

      <% if project.project_type == "iOS" %>
        <div class="col s12 l5 center">
          <%= image_tag(project.image, class: "responsive-img z-depth-2 center") %>


          <iframe src="<%= project.live_link %>" width="183px" height="391px" frameborder="0" scrolling="no"></iframe>
        </div>
      <% else %>
        <div class="col s12 l5">
          <% if project.live_link %>
            <%= link_to image_tag(project.image, class: "responsive-img z-depth-2 center"), project.live_link %>
          <% else %>
            <%= image_tag(project.image, class: "responsive-img z-depth-2 center") %>
          <% end %>
        </div>
      <% end %>

    </div>
  </div>
<% end %>

app/views/projects/index.html.erb
<div id="index-banner" class="parallax-container">
  <div class="parallax"><%= image_tag("bestroses.jpg", alt: "banner img") %></div>
  <br><br>
  <h1 class="header center white-text text-lighten-2">Portfolio</h1> 
</div>

<div class="container">
  <div class="section">
    
    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12">
        <div class="icon-block">

          <p class="light center">I created the following projects by consulting countless online references, online bootcamps, and books.</p>

          <!--Header portfolio-->
          <h2 class="center brown-text">
             My <span style="color:#F6358A"><%= params[:project_type] if params[:project_type] %></span> Projects
          </h2>

          <div class="center">

            <h5>Filter by Category:</h5>

            <% if params[:project_type] %>
              <%= link_to "View All Projects", projects_path, class: "orange-text text-darken-2" %>
              <br /><br />

            <% end %>

            <%= link_to "JavaScript", projects_path(project_type: 'JavaScript'), class:"btn waves-effect waves-light pink darken-1" %>
            | <%= link_to "Ruby on Rails", projects_path(project_type: 'Ruby on Rails'), class:"btn waves-effect waves-light pink darken-1" %>
            | <%= link_to "iOS", projects_path(project_type: 'iOS'), class:"btn waves-effect waves-light pink darken-1" %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row"> 
    <%= render 'projects', projects: @projects %>
      <% if !params[:project_type] %>
        <hr />
        <h3 class="center">
          Also see My <span style="color:#F6358A"><%= link_to "iOS Projects", projects_path(project_type: 'iOS') %></span>.

        </h3>
      <% end %>
  </div>
</div>